### ISSUE TITLE
Add "has no t2" rule for "t1 JOIN t2 ... t1.fkey = t2.pkey ... t2.pkey IS NULL" 

### ISSUE THREAD

**Issue by wholton** [sqltutor-project/sqltutor#28]

**Comment by jakecobb** [comment]
I suggest a rule with higher precedence than `DefaultIsNullRule` and `InRelationshipLoweringRule`, matching the `t2.pkey IS NULL` expression and the `{IN_RELATIONSHIP}` token and consuming both.  Will need a variant for cases where there is or is not a role label associated with the relationship.

Concrete example of the need for this rule:

``` sql
SELECT ... employee e WHERE e.super_ssn IS NULL
```

Other rules convert this to something similar to:

``` sql
SELECT ... employee e LEFT JOIN employee s WHERE e.super_ssn = s.ssn AND s.ssn IS NULL
```

Symbolic structure will eventually reach:

```
... {AND: {IN_RELATIONSHIP [e1=s, e2=e, rel=SUPERVISION]}, {IS_NULL [s.ssn]}} 
```

New rule can fire here and put in some new token kind.  Complementary new lowering rule(s) can convert that token to natural language.

**Comment by wholton** [comment]
1) Edit: May have solved earlier issue where InRelationshipLabelRule got to the InRelationshipToken first. I'm going to make a rule with higher precedence than the "InRelationshipLabelRule" and insert a "NOT_IN_RELATIONSHIP" token then create a NotInRelationshipLoweringRule. 

2) Generating "_t1_ does not have _t2_" may not be straight-forward. Under situations where we have a separate label, saying something like "each employee who does not have a department" is fine. But consider self-joins (like employee to supervisor) where there is no label on either side of the join or the label rule didn't fire for any other reason (e.g. "each employee _e1_ who does not have an employee _e2_"). One solution would be to required labels on self-joins, another would be if we had negated relationship annotations (to produce "_t1_ _negated-verbalized-relationship_ _t2_").

One further note: It seems like "IsNotNullNode" gets generated as a "NotNode" with "IsNull" within it. So we should prepare for that accordingly (I'm adding it to the issues test). Essentially we can generate the same English as what is generated when we have a join and the primary key table is not mentioned, right? e.g. "SELECT fname FROM employee WHERE super_ssn IS NOT NULL"  translates to: "Select the first name of each employee who works for a supervisor." Perhaps we can just make an IN_RELATIONSHIP token?

**Comment by jakecobb** [comment]
Minor nitpick, I don't quite like the name not-in-relationship because this isn't the inverse of in-relationship.  Something like has-relationship might be better, with a flag for "not" on the token.

2) We need the same distinction made between the current two `InRelationship`\* rules regarding whether a role label is available.  Without a role label, we want "employee who does not work for a department."  Maybe it's better to have two token kinds, one that is like `{HAS [e1=..., e2=..., not=true]}` for when a role label was available and another for verbalizing the relationship, possibly negated.  Another option is to simply mark the `{HAS}` with a flag to indicate whether the relationship needs to be verbalized and let the lowering rule make the distinction.  The third option, which I think you alluded to, is to enhance `{IN_RELATIONSHIP}` with a similar flag.

We should consider some concerns from #27 here as well, in that we want the "a/an" form for these cases.

For your last case, does that get expanded to a join by the other rules or is that only for cases with a literal comparison?

**Comment by wholton** [comment]
Yes, it would get expanded to a join, and thus become " ... supervisor.ssn IS NOT NULL ". I suppose the easiest route is to create a rule that simply drops it if there is already an InRelationshipToken which references it (which there should always be).

**Comment by wholton** [comment]
"Minor nitpick, I don't quite like the name not-in-relationship because this isn't the inverse of in-relationship. Something like has-relationship might be better, with a flag for "not" on the token."

Isn't that what we're trying to get across though, that they're explicitly not a part of the relationship (the inverse)?

**Comment by jakecobb** [comment]
For `IS NULL` sort of, but what about `IS NOT NULL`?  An invertible has-relationship can account for both of these.  The reason I don't like not-in-relationship is because it makes me think either the join condition is not present or is explicitly blocked, e.g. `employee e, employee s ... s.ssn <> e.super_ssn`, which seems like the more natural inverse.  Anyway, the naming isn't incredibly important as long as it handles both `IS NULL` and `IS NOT NULL` together and doesn't make the current `{IN_RELATIONSHIP}` rules responsible for the `IS NOT NULL` case.

**Comment by wholton** [comment]
I've uploaded some preliminary work. I'm in the process of updating it to only fire if either the nonparticipating side has a label (the IS NULL side), or we have a negated relationship annotation.

**Comment by wholton** [comment]
To note, this is largely "finished". However there are some closely related issues that I'll umbrella under this issue. I'll close it when I've finished handling IS NOT NULL and <i>negated-verbalized-relationships</i>.
